name: Azure CLI

on: [push]

defaults:
  run:
    shell: bash
    working-directory: scripts 

jobs:
  azure_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v2

      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            chmod +x cli.sh
            cli.sh